//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1076 with alias "thirdPartyScripts"
	/// <summary>_Third Party Scripts</summary>
	public partial interface IThirdPartyScripts : IPublishedContent
	{
		/// <summary>Guide: Scripts Location</summary>
		Newtonsoft.Json.Linq.JToken GuideScriptsLocation { get; }

		/// <summary>Scripts after "Opening Body" Tag</summary>
		string ScriptsAfterOpeningBodyTag { get; }

		/// <summary>Scripts after "Opening Head" Tag</summary>
		string ScriptsAfterOpeningHeadTag { get; }

		/// <summary>Scripts before "Closing Body" Tag</summary>
		string ScriptsBeforeClosingBodyTag { get; }

		/// <summary>Scripts before "Closing Head" Tag</summary>
		string ScriptsBeforeClosingHeadTag { get; }
	}

	/// <summary>_Third Party Scripts</summary>
	[PublishedContentModel("thirdPartyScripts")]
	public partial class ThirdPartyScripts : PublishedContentModel, IThirdPartyScripts
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "thirdPartyScripts";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ThirdPartyScripts(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ThirdPartyScripts, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Guide: Scripts Location: Click image to show the scripts location in html.
		///</summary>
		[ImplementPropertyType("guideScriptsLocation")]
		public Newtonsoft.Json.Linq.JToken GuideScriptsLocation
		{
			get { return GetGuideScriptsLocation(this); }
		}

		/// <summary>Static getter for Guide: Scripts Location</summary>
		public static Newtonsoft.Json.Linq.JToken GetGuideScriptsLocation(IThirdPartyScripts that) { return that.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("guideScriptsLocation"); }

		///<summary>
		/// Scripts after "Opening Body" Tag: The scripts that will be inserted after the opening body tag of each page.
		///</summary>
		[ImplementPropertyType("scriptsAfterOpeningBodyTag")]
		public string ScriptsAfterOpeningBodyTag
		{
			get { return GetScriptsAfterOpeningBodyTag(this); }
		}

		/// <summary>Static getter for Scripts after "Opening Body" Tag</summary>
		public static string GetScriptsAfterOpeningBodyTag(IThirdPartyScripts that) { return that.GetPropertyValue<string>("scriptsAfterOpeningBodyTag"); }

		///<summary>
		/// Scripts after "Opening Head" Tag: The scripts that will be inserted after the opening head tag of each page.
		///</summary>
		[ImplementPropertyType("scriptsAfterOpeningHeadTag")]
		public string ScriptsAfterOpeningHeadTag
		{
			get { return GetScriptsAfterOpeningHeadTag(this); }
		}

		/// <summary>Static getter for Scripts after "Opening Head" Tag</summary>
		public static string GetScriptsAfterOpeningHeadTag(IThirdPartyScripts that) { return that.GetPropertyValue<string>("scriptsAfterOpeningHeadTag"); }

		///<summary>
		/// Scripts before "Closing Body" Tag: The scripts that will be inserted before the closing body tag of each page.
		///</summary>
		[ImplementPropertyType("scriptsBeforeClosingBodyTag")]
		public string ScriptsBeforeClosingBodyTag
		{
			get { return GetScriptsBeforeClosingBodyTag(this); }
		}

		/// <summary>Static getter for Scripts before "Closing Body" Tag</summary>
		public static string GetScriptsBeforeClosingBodyTag(IThirdPartyScripts that) { return that.GetPropertyValue<string>("scriptsBeforeClosingBodyTag"); }

		///<summary>
		/// Scripts before "Closing Head" Tag: The scripts that will be inserted before the closing head tag of each page.
		///</summary>
		[ImplementPropertyType("scriptsBeforeClosingHeadTag")]
		public string ScriptsBeforeClosingHeadTag
		{
			get { return GetScriptsBeforeClosingHeadTag(this); }
		}

		/// <summary>Static getter for Scripts before "Closing Head" Tag</summary>
		public static string GetScriptsBeforeClosingHeadTag(IThirdPartyScripts that) { return that.GetPropertyValue<string>("scriptsBeforeClosingHeadTag"); }
	}
}
